application: beacon48app
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: helloworld.py

- url: /write
  script: preview.py

- url: /css
  static_dir: css

- url: /favicon.ico
  static_files:: favicon.ico
